### ISSUE TITLE
[建议] 背景壁纸新增动态视频格式

### ISSUE THREAD

**Issue by jackloves111** [hslr-s/sun-panel#123]
# 背景壁纸新增动态视频格式

#### 因为我是通过浏览器开发者模式测试的，这里的视频用的是外链，加到项目里后，应该是设置里上传的本地视频地址
```html
<div class="video-background">  
    <video autoplay loop muted playsinline>  
        <source src="http://127.0.0.1:3002/uploads/动态壁纸-01.mp4" type="video/mp4">  
    </video>  
</div>
```

- 如图所示，此段代码放在这个位置
![F@ZE2~~HLV}%8)} UV~LEWN](https://github.com/hslr-s/sun-panel/assets/89971817/ebec83e3-d296-434c-b21a-fffdac65e489)

- 对应的css代码
```css
.video-background {  
    position: relative;  
    width: 100%;  
    height: 100vh; /* 调整为你需要的高度 */  
    overflow: hidden;  
}  
  
.video-background video {  
    position: absolute;  
    top: 0;  
    left: 0;  
    width: 100%;  
    height: 100%;  
    object-fit: cover; /* 确保视频覆盖整个容器，可能会有一些裁剪 */  
}
```

- 因为这样可能会覆盖图片背景图，所以应该要写一个js判断，是否启用视频动态图，这样没有设置视频背景的时候，不会覆盖静态背景图

- 实际情况可能比我想象的要复杂，具体以作者的测试为准
