### ISSUE TITLE
LOGO无法调节大小

### ISSUE THREAD

**Issue by maodou6** [hslr-s/sun-panel#170]
logo无法调节大小，比如我找到了两个图标logo，但是一个大一个小，显得恨不和谐
![Uploading Snipaste_2024-01-25_23-44-20.jpg…]()

**Comment by Firfr** [comment]
在 `conf/custom` 目录下,建立`index.css`文件
写入下面内容:
```css
/* 图标大小 */
.item-icon>div>img{
    width: 100%;
    height: 100%;
}
```
这样,所有图标就都会是最大
