### ISSUE TITLE
关于非amd64平台，无法运行程序的问题，征集方案

### ISSUE THREAD

**Issue by hslr-s** [hslr-s/sun-panel#9]
首先没想到大家这么喜欢这款软件，非常感谢小伙伴们和大佬的支持。但毕竟一个人的精力有限，所以我仅编译了amd64平台的，有能力的大佬可以自行尝试编译其他平台版本使用。
因为找自动化解决方案，需要大量时间查资料和测试，但是我想把更多的时间投入在开发进度上，所以有愿意参与无私奉献的大佬、愿意提供方案或者参与维护其他平台docker镜像的，可以把方案放在此issue下，采纳后，将在readme.md署名，在此感谢了。

编译现有的需求：
1. go语言交叉编译（需支持cgo）
2. docker多平台镜像的生成方案

不仅限于上面的需求解决方案，任何相关方案否可以提供，希望各位伙伴和大佬多多提供方案，再次感谢，一起学习共同进步！

**Comment by RocCheng** [comment]
您好，哔站看到您的视频有这个需求，正好之前做过多平台构建推送，可以添加一个Github Action工作流，自动化多平台构建，并推送到Docker Hub。
看我的fork：
https://github.com/RocCheng/sun-panel/blob/master/.github/workflows/docker.yml
多平台的镜像：
https://hub.docker.com/r/roccheng/sun-panel/tags

```yml
name: 多平台构建

on: 
  # 触发条件，这里我是手动的，可以配置push自动触发
  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU # 模拟器，模拟不同平台
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx # 通过Buildx，构建多平台
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub # 这里要登陆Docker Hub，需要账户名和一个token，token去Docker Hub生成，然后要在Github项目设置里添加两个secrets，DOCKERHUB_USERNAME 和 DOCKERHUB_TOKEN
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push # 构建推送
        uses: docker/build-push-action@v4
        with:
          context: .  # 这里在项目根目录找Dockerfile构建
          platforms: linux/amd64,linux/arm64 # 可配置多个平台
          push: true 
          tags: roccheng/sun-panel # 这里要改成你的Docker Hub 名字
```
